spring:
  profiles:
    active: multiple_query
  application:
    name: hibernate
  datasource:
    url: jdbc:postgresql://localhost:5435/hibernate-db
    username: ${DB_USERNAME:hibernate-user}
    password: ${DB_PASSWORD:Password1234}
  jpa:
    hibernate:
      ddl-auto: create-drop
